/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Cliente;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.Arreglo_cliente;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
/**
 *
 * @author Alonso
 */
public class Interfaz_cliente extends javax.swing.JFrame {

    Arreglo_cliente arreglovector = new Arreglo_cliente();
    Cliente Cmodificar = new Cliente();
    Cliente Celiminar = new Cliente();
    DefaultTableModel Table = new DefaultTableModel();
    /**
     * Creates new form Interfaz
     */
    public Interfaz_cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen1= new ImageIcon(getClass().getResource("/Imagenes/logo.png"));
        Icon fondo1= new ImageIcon(imagen1.getImage().getScaledInstance(icono.getWidth(), icono.getHeight(), Image.SCALE_DEFAULT));
        icono.setIcon(fondo1);
        icono1.setIcon(fondo1);
        icono2.setIcon(fondo1);
        icono3.setIcon(fondo1);
        
        Table.addColumn("Código");
        Table.addColumn("DNI");
        Table.addColumn("Nombres");
        Table.addColumn("Apellidos");
        Table.addColumn("Fecha de nacimiento");
        Table.addColumn("Sexo");
        Table.addColumn("Email");
        Table.addColumn("Dirección");
        Table.addColumn("Distrito");
        Table.addColumn("Provincia");
        Table.addColumn("País");
        
        Table1.setModel(Table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        guardar1 = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        nacimiento = new com.toedter.calendar.JDateChooser();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        distrito = new javax.swing.JTextField();
        provincia = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        icono = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dniB = new javax.swing.JTextField();
        nombreB = new javax.swing.JTextField();
        apellidoB = new javax.swing.JTextField();
        sexoB = new javax.swing.JTextField();
        emailB = new javax.swing.JTextField();
        direccionB = new javax.swing.JTextField();
        distritoB = new javax.swing.JTextField();
        provinciaB = new javax.swing.JTextField();
        paisB = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        nacimientoB = new javax.swing.JTextField();
        icono1 = new javax.swing.JLabel();
        codigoB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        dniE = new javax.swing.JTextField();
        nombreE = new javax.swing.JTextField();
        apellidoE = new javax.swing.JTextField();
        emailE = new javax.swing.JTextField();
        direccionE = new javax.swing.JTextField();
        distritoE = new javax.swing.JTextField();
        provinciaE = new javax.swing.JTextField();
        paisE = new javax.swing.JTextField();
        buscarE = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        codigoE = new javax.swing.JTextField();
        nacimientoE = new javax.swing.JLabel();
        icono2 = new javax.swing.JLabel();
        sexoE = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        dniM = new javax.swing.JTextField();
        nombreM = new javax.swing.JTextField();
        apellidoM = new javax.swing.JTextField();
        emailM = new javax.swing.JTextField();
        direccionM = new javax.swing.JTextField();
        distritoM = new javax.swing.JTextField();
        provinciaM = new javax.swing.JTextField();
        paisM = new javax.swing.JTextField();
        buscarM = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        nacimientoM = new com.toedter.calendar.JDateChooser();
        masculinoM = new javax.swing.JRadioButton();
        femeninoM = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        codigoM = new javax.swing.JTextField();
        nacimientoModificar = new javax.swing.JLabel();
        icono3 = new javax.swing.JLabel();
        sexoMO = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1143, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1143, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1155, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1143, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(14, 176, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datos del cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 107, -1));

        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 539, 119, 35));

        guardar1.setText("GUARDAR");
        guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(guardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 539, 142, 35));

        Listar.setText("LISTAR");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        jPanel1.add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 600, 142, 33));

        jLabel2.setText("DNI:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 47, 75, -1));

        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 87, 113, -1));

        jLabel5.setText("Apellidos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 132, 113, -1));

        jLabel7.setText("Fecha de nacimiento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 177, -1, -1));

        jLabel8.setText("Sexo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 235, -1, -1));

        jLabel10.setText("Email:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 286, -1, -1));

        jLabel11.setText("Dirección:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 330, -1, -1));

        jLabel12.setText("Distrito:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 375, -1, -1));

        jLabel13.setText("Provincia:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 423, -1, -1));
        jPanel1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 47, 192, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 91, 192, -1));
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 131, 192, -1));
        jPanel1.add(nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 171, 192, -1));

        buttonGroup1.add(masculino);
        masculino.setText("Masculino");
        jPanel1.add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 233, -1, -1));

        buttonGroup1.add(femenino);
        femenino.setText("Femenino");
        jPanel1.add(femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 233, -1, -1));

        jLabel14.setText("País:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 466, -1, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 283, 193, -1));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 327, 193, -1));
        jPanel1.add(distrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 372, 193, -1));
        jPanel1.add(provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 420, 193, -1));
        jPanel1.add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 463, 193, -1));

        jPanel10.setBackground(new java.awt.Color(14, 176, 68));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Clientes"));
        jPanel10.setForeground(new java.awt.Color(14, 176, 68));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 840, 350));
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));

        jTabbedPane1.addTab("Guardar ", jPanel1);

        jPanel4.setBackground(new java.awt.Color(14, 176, 68));

        jPanel7.setBackground(new java.awt.Color(14, 176, 68));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Buscar cliente:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 128, -1));

        jLabel15.setText("DNI:");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 83, 75, -1));

        jLabel16.setText("Nombres:");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 120, 137, -1));

        jLabel17.setText("Apellidos:");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 163, 137, -1));

        jLabel18.setText("Fecha de nacimiento:");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 203, -1, -1));

        jLabel19.setText("Sexo:");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 236, -1, -1));

        jLabel20.setText("Email:");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 281, -1, -1));

        jLabel21.setText("Dirección:");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 321, -1, -1));

        jLabel22.setText("Distrito:");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 358, -1, -1));

        jLabel23.setText("Provincia:");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 398, -1, -1));

        jLabel24.setText("País:");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 432, -1, -1));
        jPanel7.add(dniB, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 77, 193, -1));
        jPanel7.add(nombreB, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 117, 193, -1));
        jPanel7.add(apellidoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 157, 193, -1));
        jPanel7.add(sexoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 233, 193, -1));
        jPanel7.add(emailB, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 275, 193, -1));
        jPanel7.add(direccionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 315, 193, -1));
        jPanel7.add(distritoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 355, 193, -1));
        jPanel7.add(provinciaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 395, 193, -1));
        jPanel7.add(paisB, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 429, 193, -1));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel7.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 225, 172, 38));
        jPanel7.add(nacimientoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 197, 193, -1));
        jPanel7.add(icono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));
        jPanel7.add(codigoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 37, 193, -1));

        jLabel4.setText("Código:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 40, 75, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Buscar", jPanel4);

        jPanel9.setBackground(new java.awt.Color(14, 176, 68));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setText("Eliminar cliente:");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 128, -1));

        jLabel37.setText("DNI:");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 100, 75, -1));

        jLabel38.setText("Nombres:");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 140, 166, -1));

        jLabel39.setText("Apellidos:");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 180, 166, -1));

        jLabel40.setText("Fecha de nacimiento:");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 216, -1, -1));

        jLabel41.setText("Sexo:");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 250, -1, -1));

        jLabel42.setText("Email:");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 272, -1, 25));

        jLabel43.setText("Dirección:");
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 315, -1, -1));

        jLabel44.setText("Distrito:");
        jPanel9.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 352, -1, -1));

        jLabel45.setText("Provincia:");
        jPanel9.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 392, -1, -1));

        jLabel46.setText("País:");
        jPanel9.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 426, -1, -1));
        jPanel9.add(dniE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 97, 193, -1));
        jPanel9.add(nombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 137, 193, -1));
        jPanel9.add(apellidoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 177, 193, -1));
        jPanel9.add(emailE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 272, 193, -1));
        jPanel9.add(direccionE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 309, 193, -1));
        jPanel9.add(distritoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 349, 193, -1));
        jPanel9.add(provinciaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 389, 193, -1));
        jPanel9.add(paisE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 423, 193, -1));

        buscarE.setText("Buscar");
        buscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEActionPerformed(evt);
            }
        });
        jPanel9.add(buscarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 149, 172, 38));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel9.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 216, 172, 43));

        jLabel47.setText("Código:");
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 60, 113, -1));
        jPanel9.add(codigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 57, 193, -1));
        jPanel9.add(nacimientoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 217, 193, -1));
        jPanel9.add(icono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));
        jPanel9.add(sexoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 235, 193, -1));

        jTabbedPane1.addTab("Eliminar", jPanel9);

        jPanel8.setBackground(new java.awt.Color(14, 176, 68));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("Modificar cliente:");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 128, -1));

        jLabel26.setText("DNI:");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 71, 75, -1));

        jLabel27.setText("Nombres:");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 115, 206, -1));

        jLabel28.setText("Apellidos:");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 144, 206, 27));

        jLabel29.setText("Fecha de nacimiento:");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 195, -1, -1));

        jLabel30.setText("Sexo:");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 219, -1, -1));

        jLabel31.setText("Email:");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 243, -1, 25));

        jLabel32.setText("Dirección:");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 301, -1, -1));

        jLabel33.setText("Distrito:");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 349, -1, -1));

        jLabel34.setText("Provincia:");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 392, -1, -1));

        jLabel35.setText("País:");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 423, -1, -1));
        jPanel8.add(dniM, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 68, 193, -1));
        jPanel8.add(nombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 112, 193, -1));
        jPanel8.add(apellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 146, 193, -1));
        jPanel8.add(emailM, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 253, 193, -1));
        jPanel8.add(direccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 298, 193, -1));
        jPanel8.add(distritoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 346, 193, -1));
        jPanel8.add(provinciaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 389, 193, -1));

        paisM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisMActionPerformed(evt);
            }
        });
        jPanel8.add(paisM, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 423, 193, -1));

        buscarM.setText("Buscar");
        buscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMActionPerformed(evt);
            }
        });
        jPanel8.add(buscarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 161, 172, 38));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel8.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 243, 172, 43));
        jPanel8.add(nacimientoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 189, 172, -1));

        buttonGroup2.add(masculinoM);
        masculinoM.setText("Masculino");
        jPanel8.add(masculinoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 217, -1, -1));

        buttonGroup2.add(femeninoM);
        femeninoM.setText("Femenino");
        jPanel8.add(femeninoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 217, -1, -1));

        jLabel6.setText("Código:");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 37, 159, -1));

        codigoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoMActionPerformed(evt);
            }
        });
        jPanel8.add(codigoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 34, 193, -1));
        jPanel8.add(nacimientoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 195, 92, -1));
        jPanel8.add(icono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));
        jPanel8.add(sexoMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 217, 92, -1));

        jTabbedPane1.addTab("Modificar", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        if(Celiminar.getApellido()!="Error")
        {
            arreglovector.eliminar(Celiminar);
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            arreglovector.grabarModificareliminar();
        }else{
            JOptionPane.showMessageDialog(null, "No existe código",
                            "Error",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEActionPerformed
        // TODO add your handling code here:
        int cod = 0;
        cod = Integer.parseInt(codigoE.getText());
        Celiminar=arreglovector.buscarcodigo(cod);
        
        if(Celiminar.getApellido() !="Error"){
            apellidoE.setText(Celiminar.getApellido());
            dniE.setText(String.valueOf(Celiminar.getDni()));
            nombreE.setText(Celiminar.getNombre());
            apellidoE.setText(Celiminar.getApellido());
            nacimientoE.setText(Celiminar.getNacimiento());
            sexoE.setText(Celiminar.getSexo());
            emailE.setText(Celiminar.getEmail());
            direccionE.setText(Celiminar.getDireccion());
            distritoE.setText(Celiminar.getDistrito());
            provinciaE.setText(Celiminar.getProvincia());
            paisE.setText(Celiminar.getPais());
        }else{
            JOptionPane.showMessageDialog(null, "No existe código", "Error",
                        JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_buscarEActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        
        String apeM;
        String nom;
        int dnii ;
        //String fecha;
        String sex = null;
        String ema;
        String dir;
        String dis;
        String prov;
        String pa;
        apeM=apellidoM.getText();
        
        nom = nombreM.getText();
        dnii = Integer.parseInt(dniM.getText());
        SimpleDateFormat ff = new SimpleDateFormat("dd-MM-yyyy");
        String date = ff.format(nacimientoM.getDate());
        //fecha=nacimientoM.getToolTipText();
        if(masculinoM.isSelected()){
            sex="Masculino";
        }else{
            sex="Femenino";
        }
        ema=emailM.getText();
        dir=direccionM.getText();
        dis=distritoM.getText();
        prov=provinciaM.getText();
        pa=paisM.getText();
        
        boolean estado = arreglovector.modificar(Cmodificar, dnii, nom, apeM, date, sex, ema, dir
                    , dis, prov, pa);

        if(estado == true){
            JOptionPane.showMessageDialog(null, "Registro Modificado");
            arreglovector.grabarModificareliminar();
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "No se puede Modificar",
                "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void buscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMActionPerformed
        // TODO add your handling code here:
        int cod=0;
        cod=Integer.parseInt(codigoM.getText());
        Cmodificar = arreglovector.buscarcodigo(cod);

        if(Cmodificar.getApellido() != "Error"){
            dniM.setText(String.valueOf(Cmodificar.getDni()));
            nombreM.setText(Cmodificar.getNombre());
            apellidoM.setText(Cmodificar.getApellido());
            //nacimientoM.setToolTipText(Cmodificar.getNacimiento());
            
            nacimientoModificar.setText(Cmodificar.getNacimiento());
            
            sexoMO.setText(Cmodificar.getSexo());
            //nacimientoM.setDateFormatString(Cmodificar.getNacimiento());
            
           /* if(masculinoM.isShowing()){
                masculinoM.setSelected(rootPaneCheckingEnabled);
            }
                else{
                        femeninoM.setSelected(rootPaneCheckingEnabled);
                        }
            
            
            
            
            /*if(masculino.isSelected()){
                sex="Masculino";
            }else{
                sex="Femenino";
            }*/
            /*sexo2.setText(Cmodificar.getSexo());*/
            emailM.setText(Cmodificar.getEmail());
            direccionM.setText(Cmodificar.getDireccion());
            distritoM.setText(Cmodificar.getDistrito());
            provinciaM.setText(Cmodificar.getProvincia());
            paisM.setText(Cmodificar.getPais());
        }else{
            JOptionPane.showMessageDialog(null, "No existe codigo",
                "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarMActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        int cod=0;
        cod=Integer.parseInt(codigoB.getText());
        Cliente c = arreglovector.buscarcodigo(cod);

        /*SimpleDateFormat ff = new SimpleDateFormat("dd-MM-yyyy");
        String date = ff.format(nacimiento.getDate());*/

        if(c.getApellido()!="Error"){
            dniB.setText(String.valueOf(c.getDni()));
            nombreB.setText(c.getNombre());
            apellidoB.setText(c.getApellido());
            nacimientoB.setText(c.getNacimiento());
            sexoB.setText(c.getSexo());
            emailB.setText(c.getEmail());
            direccionB.setText(c.getDireccion());
            distritoB.setText(c.getDistrito());
            provinciaB.setText(c.getProvincia());
            paisB.setText(c.getPais());
        }else{
            JOptionPane.showMessageDialog(null, "No existe dni",
                "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here:

        Table.getDataVector().removeAllElements();

        /*SimpleDateFormat ff = new SimpleDateFormat("dd-MM-yyyy");
        String date = ff.format(nacimiento.getDate());*/

        String [] filas = new String[11];

        for(int i=0; i<arreglovector.filas();i++){
            filas[0] = String.valueOf(arreglovector.get(i).getCodigo());
            filas[1] = String.valueOf(arreglovector.get(i).getDni());
            filas[2] = arreglovector.get(i).getNombre();
            filas[3] = arreglovector.get(i).getApellido();
            filas[4] = arreglovector.get(i).getNacimiento();
            filas[5] = arreglovector.get(i).getSexo();
            filas[6] = arreglovector.get(i).getEmail();
            filas[7] = arreglovector.get(i).getDireccion();
            filas[8] = arreglovector.get(i).getDistrito();
            filas[9] = arreglovector.get(i).getProvincia();
            filas[10] = arreglovector.get(i).getPais();
            Table.addRow(filas);
        }
    }//GEN-LAST:event_ListarActionPerformed

    private void guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar1ActionPerformed
        // TODO add your handling code here:

        int cod = 0;
        int dnii ;
        String nom;
        String ape;
        String fecha;
        String sex = null;
        String ema;
        String dir;
        String dis;
        String prov;
        String pa;

        cod = arreglovector.correlativo();
if(dni.getText().isEmpty() || nombre.getText().isEmpty() || apellido.getText().isEmpty()
               || email.getText().isEmpty() || direccion.getText().isEmpty()||distrito.getText().isEmpty()
                ||provincia.getText().isEmpty()||pais.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"NO dejar campos vacíos");
        }
else{
        dnii = Integer.parseInt(dni.getText());
        nom=nombre.getText();
        ape=apellido.getText();

        SimpleDateFormat ff = new SimpleDateFormat("dd-MM-yyyy");
        String date = ff.format(nacimiento.getDate());
        /*fecha=nacimiento.getToolTipText();*/
        if(masculino.isSelected()){
            sex="Masculino";
        }else{
            sex="Femenino";
        }
        /*filas[4]=sexo;*/

        ema=email.getText();
        dir=direccion.getText();
        dis=distrito.getText();
        prov=provincia.getText();
        pa=pais.getText();

        Cliente c = new Cliente();

        c.setCodigo(cod);
        c.setDni(dnii);
        c.setNombre(nom);
        c.setApellido(ape);
        c.setNacimiento(date);
        c.setSexo(sex);
        c.setEmail(ema);
        c.setDireccion(dir);
        c.setDistrito(dis);
        c.setProvincia(prov);
        c.setPais(pa);
        arreglovector.agregar_array(c);
        arreglovector.grabarEnArchivo(c);
}
        dni.setText("");
        nombre.setText("");
        apellido.setText("");
        email.setText("");
        email.setText("");
        direccion.setText("");
        distrito.setText("");
        provincia.setText("");
        pais.setText("");
        
        
    }//GEN-LAST:event_guardar1ActionPerformed

    private void paisMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
       Administrador inic = new Administrador();
       inic.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void codigoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Listar;
    private javax.swing.JTable Table1;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField apellidoB;
    private javax.swing.JTextField apellidoE;
    private javax.swing.JTextField apellidoM;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscarE;
    private javax.swing.JButton buscarM;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField codigoB;
    private javax.swing.JTextField codigoE;
    private javax.swing.JTextField codigoM;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField direccionB;
    private javax.swing.JTextField direccionE;
    private javax.swing.JTextField direccionM;
    private javax.swing.JTextField distrito;
    private javax.swing.JTextField distritoB;
    private javax.swing.JTextField distritoE;
    private javax.swing.JTextField distritoM;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField dniB;
    private javax.swing.JTextField dniE;
    private javax.swing.JTextField dniM;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emailB;
    private javax.swing.JTextField emailE;
    private javax.swing.JTextField emailM;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JRadioButton femeninoM;
    private javax.swing.JButton guardar1;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel icono1;
    private javax.swing.JLabel icono2;
    private javax.swing.JLabel icono3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JRadioButton masculinoM;
    private javax.swing.JButton modificar;
    private com.toedter.calendar.JDateChooser nacimiento;
    private javax.swing.JTextField nacimientoB;
    private javax.swing.JLabel nacimientoE;
    private com.toedter.calendar.JDateChooser nacimientoM;
    private javax.swing.JLabel nacimientoModificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombreB;
    private javax.swing.JTextField nombreE;
    private javax.swing.JTextField nombreM;
    private javax.swing.JTextField pais;
    private javax.swing.JTextField paisB;
    private javax.swing.JTextField paisE;
    private javax.swing.JTextField paisM;
    private javax.swing.JTextField provincia;
    private javax.swing.JTextField provinciaB;
    private javax.swing.JTextField provinciaE;
    private javax.swing.JTextField provinciaM;
    private javax.swing.JTextField sexoB;
    private javax.swing.JLabel sexoE;
    private javax.swing.JLabel sexoMO;
    // End of variables declaration//GEN-END:variables
}
