/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.Arreglo_proveedor;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import model.Proveedor;
/**
 *
 * @author Alonso
 */
public class Interfaz_Proveedor extends javax.swing.JFrame {

    Arreglo_proveedor arreglovector = new Arreglo_proveedor();
    Proveedor Pmodificar = new Proveedor();
    Proveedor Peliminar = new Proveedor();
    DefaultTableModel Table = new DefaultTableModel();
    
    public Interfaz_Proveedor() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen1= new ImageIcon(getClass().getResource("/Imagenes/logo.png"));
        Icon fondo1= new ImageIcon(imagen1.getImage().getScaledInstance(iconoprove.getWidth(), iconoprove.getHeight(), Image.SCALE_DEFAULT));
        iconoprove.setIcon(fondo1);
        iconoprove1.setIcon(fondo1);
        iconoprove2.setIcon(fondo1);
        iconoprove3.setIcon(fondo1);
        Table.addColumn("Código");
        Table.addColumn("RUC");
        Table.addColumn("Razón social");
        Table.addColumn("Dirección");
        Table.addColumn("Contacto 1");
        Table.addColumn("Contacto 2");
        Table.addColumn("Página Web");
        Table.addColumn("Sucursal");
        
        Table1.setModel(Table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ruc = new javax.swing.JTextField();
        razon = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono1 = new javax.swing.JTextField();
        telefono2 = new javax.swing.JTextField();
        web = new javax.swing.JTextField();
        sucursal = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        guardar1 = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        iconoprove = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rucB = new javax.swing.JLabel();
        razonB = new javax.swing.JLabel();
        direccionB = new javax.swing.JLabel();
        telefono1B = new javax.swing.JLabel();
        telefono2B = new javax.swing.JLabel();
        sucursalB = new javax.swing.JLabel();
        webB = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        codigoB = new javax.swing.JTextField();
        iconoprove1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rucM = new javax.swing.JTextField();
        razonM = new javax.swing.JTextField();
        direccionM = new javax.swing.JTextField();
        telefono1M = new javax.swing.JTextField();
        telefono2M = new javax.swing.JTextField();
        webM = new javax.swing.JTextField();
        sucursalM = new javax.swing.JTextField();
        buscarM = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        codigoM = new javax.swing.JTextField();
        iconoprove2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        rucB1 = new javax.swing.JLabel();
        razonB1 = new javax.swing.JLabel();
        direccionB1 = new javax.swing.JLabel();
        telefono1B1 = new javax.swing.JLabel();
        telefono2B1 = new javax.swing.JLabel();
        sucursalB1 = new javax.swing.JLabel();
        webB1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        codigoE = new javax.swing.JTextField();
        buscarE = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        iconoprove3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1086, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1086, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(14, 176, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datos del Proveedor:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 133, -1));

        jLabel2.setText("RUC:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 52, 116, -1));

        jLabel3.setText("Razón Social:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 92, 116, -1));

        jLabel4.setText("Número de contacto 1:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 172, 148, -1));

        jLabel5.setText("Dirección:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 132, 116, -1));

        jLabel6.setText("Número de contacto 2:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 212, 136, -1));

        jLabel7.setText("Página Web:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 252, 116, -1));

        jLabel8.setText("Sucursal:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 292, 116, -1));
        jPanel1.add(ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 49, 137, -1));
        jPanel1.add(razon, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 89, 137, -1));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 129, 137, -1));
        jPanel1.add(telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 169, 137, -1));
        jPanel1.add(telefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 209, 137, -1));
        jPanel1.add(web, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 249, 137, -1));
        jPanel1.add(sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 289, 137, -1));

        Cancelar.setText("VOLVER");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 393, 119, 35));

        guardar1.setText("GUARDAR");
        guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(guardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 393, 142, 35));

        Listar.setText("LISTAR");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        jPanel1.add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 462, 142, 33));

        jPanel7.setBackground(new java.awt.Color(14, 176, 68));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Proveedores"));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 620, 420));
        jPanel1.add(iconoprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));

        jTabbedPane1.addTab("Guardar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(14, 176, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Buscar Proveedor:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 15, 107, -1));

        jLabel18.setText("RUC:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 71, 116, -1));

        jLabel19.setText("Razón Social:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 105, 116, -1));

        jLabel20.setText("Dirección:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 139, 116, -1));

        jLabel21.setText("Número de contacto 1:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 173, 136, -1));

        jLabel22.setText("Número de contacto 2:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 219, 136, -1));

        jLabel23.setText("Página Web:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 253, 116, -1));

        jLabel24.setText("Sucursal:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 295, 116, -1));
        jPanel2.add(rucB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 71, 105, -1));
        jPanel2.add(razonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 105, 105, -1));
        jPanel2.add(direccionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 139, 105, -1));
        jPanel2.add(telefono1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 162, 105, -1));
        jPanel2.add(telefono2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 219, 105, -1));
        jPanel2.add(sucursalB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 295, 105, -1));
        jPanel2.add(webB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 253, 105, -1));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 162, 172, 38));

        jLabel25.setText("Código");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 40, 43, -1));

        codigoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBActionPerformed(evt);
            }
        });
        jPanel2.add(codigoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 71, -1));
        jPanel2.add(iconoprove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));

        jTabbedPane1.addTab("Buscar", jPanel2);

        jPanel5.setBackground(new java.awt.Color(14, 176, 68));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Modificar Proveedor:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 151, -1));

        jLabel10.setText("Código:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 53, 116, -1));

        jLabel11.setText("Razón Social:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 124, 116, -1));

        jLabel12.setText("Número de contacto 1:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 201, 148, -1));

        jLabel13.setText("Dirección:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 161, 116, -1));

        jLabel14.setText("Número de contacto 2:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 242, 136, -1));

        jLabel15.setText("Página Web:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 282, 116, -1));

        jLabel16.setText("Sucursal:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 313, 116, -1));
        jPanel5.add(rucM, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 84, 137, -1));
        jPanel5.add(razonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 124, 137, -1));
        jPanel5.add(direccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 158, 137, -1));
        jPanel5.add(telefono1M, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 198, 137, -1));
        jPanel5.add(telefono2M, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 239, 137, -1));
        jPanel5.add(webM, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 279, 137, -1));
        jPanel5.add(sucursalM, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 313, 137, -1));

        buscarM.setText("Buscar");
        buscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMActionPerformed(evt);
            }
        });
        jPanel5.add(buscarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 195, 172, 38));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel5.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 123, 180, 43));

        jLabel26.setText("RUC:");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 90, 116, -1));
        jPanel5.add(codigoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 50, 137, -1));
        jPanel5.add(iconoprove2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));

        jTabbedPane1.addTab("Modificar", jPanel5);

        jPanel6.setBackground(new java.awt.Color(14, 176, 68));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("Buscar Proveedor:");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 15, 107, -1));

        jLabel28.setText("RUC:");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 71, 116, -1));

        jLabel29.setText("Razón Social:");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 105, 116, -1));

        jLabel30.setText("Dirección:");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 150, 116, -1));

        jLabel31.setText("Número de contacto 1:");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 184, 136, -1));

        jLabel32.setText("Número de contacto 2:");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 230, 136, -1));

        jLabel33.setText("Página Web:");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 278, 116, -1));

        jLabel34.setText("Sucursal:");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 320, 116, -1));
        jPanel6.add(rucB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 71, 105, -1));
        jPanel6.add(razonB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 105, 105, -1));
        jPanel6.add(direccionB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 139, 105, -1));
        jPanel6.add(telefono1B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 184, 105, -1));
        jPanel6.add(telefono2B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 217, 105, -1));
        jPanel6.add(sucursalB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 105, -1));
        jPanel6.add(webB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 278, 105, -1));

        jLabel35.setText("Código");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 40, 43, -1));

        codigoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoEActionPerformed(evt);
            }
        });
        jPanel6.add(codigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 37, 71, -1));

        buscarE.setText("Buscar");
        buscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEActionPerformed(evt);
            }
        });
        jPanel6.add(buscarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 139, 172, 38));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel6.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 217, 172, 43));
        jPanel6.add(iconoprove3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));

        jTabbedPane1.addTab("Eliminar", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        if(Peliminar.getRazon()!="Error")
        {
            arreglovector.eliminar(Peliminar);
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            arreglovector.grabarModificareliminar();
        }else{
            JOptionPane.showMessageDialog(null, "No existe código",
                "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEActionPerformed
        // TODO add your handling code here:
        int cod = 0;
        cod = Integer.parseInt(codigoE.getText());
        Peliminar=arreglovector.buscarcodigo(cod);

        if(Peliminar.getRazon() !="Error"){
            rucB1.setText(String.valueOf(Peliminar.getRUC()));
            razonB1.setText(Peliminar.getRazon());
            direccionB1.setText(Peliminar.getDireccion());
            telefono1B1.setText(String.valueOf(Peliminar.getTelefono1()));
            telefono2B1.setText(String.valueOf(Peliminar.getTelefono2()));
            webB1.setText(Peliminar.getWeb());
            sucursalB1.setText(Peliminar.getSucursal());
        }else{
            JOptionPane.showMessageDialog(null, "No existe código", "Error",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarEActionPerformed

    private void codigoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoEActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:

        int ruc;
        String ra;
        String dir ;
        int tel1;
        int tel2;
        String w;
        String suc;

        ruc = Integer.parseInt(rucM.getText());
        ra = razonM.getText();
        dir = direccionM.getText();
        tel1 = Integer.parseInt(telefono1M.getText());
        tel2 = Integer.parseInt(telefono2M.getText());
        w = webM.getText();
        suc = sucursalM.getText();

        boolean estado = arreglovector.modificar(Pmodificar, ruc, ra,
            dir, tel1, tel2, w, suc);

        if(estado == true){
            JOptionPane.showMessageDialog(null, "Registro Modificado");
            arreglovector.grabarModificareliminar();
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "No se puede Modificar",
                "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void buscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMActionPerformed
        // TODO add your handling code here:
        int cod=0;
        cod=Integer.parseInt(codigoM.getText());
        Pmodificar = arreglovector.buscarcodigo(cod);

        if(Pmodificar.getRazon() != "Error"){
            rucM.setText(String.valueOf(Pmodificar.getRUC()));
            razonM.setText(Pmodificar.getRazon());
            direccionM.setText(Pmodificar.getDireccion());
            telefono1M.setText(String.valueOf(Pmodificar.getTelefono1()));
            telefono2M.setText(String.valueOf(Pmodificar.getTelefono2()));
            webM.setText(Pmodificar.getWeb());
            sucursalM.setText(Pmodificar.getSucursal());
        }else{
            JOptionPane.showMessageDialog(null, "No existe codigo",
                "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarMActionPerformed

    private void codigoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        int cod=0;
        cod=Integer.parseInt(codigoB.getText());
        Proveedor p = arreglovector.buscarcodigo(cod);
        if(p.getRazon()!="Error"){
            rucB.setText(String.valueOf(p.getRUC()));
            razonB.setText(p.getRazon());
            direccionB.setText(p.getDireccion());
            telefono1B.setText(String.valueOf(p.getTelefono1()));
            telefono2B.setText(String.valueOf(p.getTelefono2()));
            webB.setText(p.getWeb());
            sucursalB.setText(p.getSucursal());
        }else{
            JOptionPane.showMessageDialog(null, "No existe proveedor",
                "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here:

        Table.getDataVector().removeAllElements();

        /*SimpleDateFormat ff = new SimpleDateFormat("dd-MM-yyyy");
        String date = ff.format(nacimiento.getDate());*/

        String [] filas = new String[8];

        for(int i=0; i<arreglovector.filas();i++){
            filas[0] = String.valueOf(arreglovector.get(i).getCodigo());
            filas[1] = String.valueOf(arreglovector.get(i).getRUC());
            filas[2] = arreglovector.get(i).getRazon();
            filas[3] = arreglovector.get(i).getDireccion();
            filas[4] = String.valueOf(arreglovector.get(i).getTelefono1());
            filas[5] = String.valueOf(arreglovector.get(i).getTelefono2());
            filas[6] = arreglovector.get(i).getWeb();
            filas[7] = arreglovector.get(i).getSucursal();
            Table.addRow(filas);
        }
    }//GEN-LAST:event_ListarActionPerformed

    private void guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar1ActionPerformed
        // TODO add your handling code here:

        int cod = 0;
        int r;
        String raz;
        String dir;
        int tel1;
        int tel2;
        String pagina;
        String sucur;

        cod = arreglovector.correlativo();
        if(ruc.getText().isEmpty() || razon.getText().isEmpty() || direccion.getText().isEmpty()
           || telefono1.getText().isEmpty() || telefono2.getText().isEmpty()||web.getText().isEmpty()
                ||sucursal.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"NO dejar carmpos vacíos");
        }
        else
        {
        r= Integer.parseInt(ruc.getText());
        raz=razon.getText();
        dir=direccion.getText();
        tel1=Integer.parseInt(telefono1.getText());
        tel2=Integer.parseInt(telefono2.getText());
        pagina = web.getText();
        sucur = sucursal.getText();

        Proveedor p = new Proveedor();

        p.setCodigo(cod);
        p.setRUC(r);
        p.setRazon(raz);
        p.setDireccion(dir);
        p.setTelefono1(tel1);
        p.setTelefono2(tel2);
        p.setWeb(pagina);
        p.setSucursal(sucur);
        arreglovector.agregar_array(p);
        arreglovector.grabarEnArchivo(p);
        }
        ruc.setText("");
        razon.setText("");
        direccion.setText("");
        telefono1.setText("");
        telefono2.setText("");
        sucursal.setText("");
    }//GEN-LAST:event_guardar1ActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        dispose();
        Administrador inic = new Administrador();
        inic.setVisible(true);
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Listar;
    private javax.swing.JTable Table1;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscarE;
    private javax.swing.JButton buscarM;
    private javax.swing.JTextField codigoB;
    private javax.swing.JTextField codigoE;
    private javax.swing.JTextField codigoM;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel direccionB;
    private javax.swing.JLabel direccionB1;
    private javax.swing.JTextField direccionM;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guardar1;
    private javax.swing.JLabel iconoprove;
    private javax.swing.JLabel iconoprove1;
    private javax.swing.JLabel iconoprove2;
    private javax.swing.JLabel iconoprove3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField razon;
    private javax.swing.JLabel razonB;
    private javax.swing.JLabel razonB1;
    private javax.swing.JTextField razonM;
    private javax.swing.JTextField ruc;
    private javax.swing.JLabel rucB;
    private javax.swing.JLabel rucB1;
    private javax.swing.JTextField rucM;
    private javax.swing.JTextField sucursal;
    private javax.swing.JLabel sucursalB;
    private javax.swing.JLabel sucursalB1;
    private javax.swing.JTextField sucursalM;
    private javax.swing.JTextField telefono1;
    private javax.swing.JLabel telefono1B;
    private javax.swing.JLabel telefono1B1;
    private javax.swing.JTextField telefono1M;
    private javax.swing.JTextField telefono2;
    private javax.swing.JLabel telefono2B;
    private javax.swing.JLabel telefono2B1;
    private javax.swing.JTextField telefono2M;
    private javax.swing.JTextField web;
    private javax.swing.JLabel webB;
    private javax.swing.JLabel webB1;
    private javax.swing.JTextField webM;
    // End of variables declaration//GEN-END:variables
}
