/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.Arreglo_producto;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import model.Producto;
/**
 *
 * @author tello
 */
public class Interfaz_Productos extends javax.swing.JFrame {
  Arreglo_producto arreglovector=new Arreglo_producto();
  Producto Dmodificar=new Producto();
  Producto Deliminar=new Producto();
  DefaultTableModel Table = new DefaultTableModel();
    /**
     * Creates new form Interfaz
     */
    public Interfaz_Productos() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen1= new ImageIcon(getClass().getResource("/Imagenes/logo.png"));
        Icon fondo1= new ImageIcon(imagen1.getImage().getScaledInstance(iconopro.getWidth(), iconopro.getHeight(), Image.SCALE_DEFAULT));
        iconopro.setIcon(fondo1);
        iconopro1.setIcon(fondo1);
        iconopro2.setIcon(fondo1);
        iconopro3.setIcon(fondo1);
        Table.addColumn("Código");
        Table.addColumn("Nombre");
        Table.addColumn("Color:");
        Table.addColumn("Tamaño:");
        Table.addColumn("Stock:");
        Table.addColumn("Precio:");
        Table.addColumn("Costo:");
        Table.addColumn("Edad Recomendada");
        
        jTable1.setModel(Table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Costo = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        Color = new javax.swing.JComboBox<>();
        Pequeño = new javax.swing.JRadioButton();
        Mediano = new javax.swing.JRadioButton();
        Grande = new javax.swing.JRadioButton();
        Stock = new javax.swing.JSpinner();
        Cerrar = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        iconopro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        B_Codigo = new javax.swing.JTextField();
        B_Nombre = new javax.swing.JTextField();
        B_Color = new javax.swing.JTextField();
        B_Tamaño = new javax.swing.JTextField();
        B_Stock = new javax.swing.JTextField();
        B_Precio = new javax.swing.JTextField();
        B_Edad = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        B_Costo = new javax.swing.JTextField();
        iconopro1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        M_Codigo = new javax.swing.JTextField();
        M_Nombre = new javax.swing.JTextField();
        M_Color = new javax.swing.JTextField();
        M_Tamaño = new javax.swing.JTextField();
        M_Stock = new javax.swing.JTextField();
        M_Costo = new javax.swing.JTextField();
        M_Precio = new javax.swing.JTextField();
        M_Edad = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        Listar2 = new javax.swing.JButton();
        iconopro2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        E_Codigo = new javax.swing.JTextField();
        E_Nombre = new javax.swing.JTextField();
        E_Color = new javax.swing.JTextField();
        E_Tamaño = new javax.swing.JTextField();
        E_Stock = new javax.swing.JTextField();
        E_Costo = new javax.swing.JTextField();
        E_Precio = new javax.swing.JTextField();
        E_Edad = new javax.swing.JTextField();
        Listar3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        iconopro3 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(14, 176, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Datos de Productos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 57, -1, -1));

        jLabel11.setText("Color:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 100, -1, -1));

        jLabel12.setText("Tamaño");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 139, -1, -1));

        jLabel13.setText("Stock");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 192, -1, -1));

        jLabel14.setText("Precio");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 234, -1, -1));

        jLabel15.setText("Costo");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 278, -1, -1));

        jLabel16.setText("Edad Recomendada:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 363, -1, -1));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 47, 137, 32));
        jPanel1.add(Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 278, 133, 37));
        jPanel1.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 231, 133, 35));

        buttonGroup2.add(jCheckBox1);
        jCheckBox1.setText("+3 años");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 361, -1, -1));

        buttonGroup2.add(jCheckBox2);
        jCheckBox2.setText("+5 años");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 361, -1, -1));

        buttonGroup2.add(jCheckBox3);
        jCheckBox3.setText("+7 años");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 361, -1, -1));

        buttonGroup2.add(jCheckBox4);
        jCheckBox4.setText("+9 años");
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 361, -1, -1));

        Color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Verde", "Morado" }));
        jPanel1.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 91, 116, 28));

        buttonGroup3.add(Pequeño);
        Pequeño.setText("Pequeño");
        jPanel1.add(Pequeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 137, -1, -1));

        buttonGroup3.add(Mediano);
        Mediano.setText("Mediano");
        jPanel1.add(Mediano, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 137, -1, -1));

        buttonGroup3.add(Grande);
        Grande.setText("Grande");
        jPanel1.add(Grande, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 137, -1, -1));
        jPanel1.add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 185, 85, 31));

        Cerrar.setText("VOLVER");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        jPanel1.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 140, 40));

        Listar.setText("LISTAR");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        jPanel1.add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 130, 40));

        Guardar.setText("GUARDAR");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 130, 40));

        jPanel5.setBackground(new java.awt.Color(14, 176, 68));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de productos"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 570, 340));
        jPanel1.add(iconopro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));

        jTabbedPane1.addTab("INICIO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(14, 176, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel3.setText("Color:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel4.setText("Tamaño:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel5.setText("Precio:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jLabel6.setText("Stock:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel7.setText("Edad Recomendada:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));
        jPanel2.add(B_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 154, 31));
        jPanel2.add(B_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 154, 34));
        jPanel2.add(B_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 154, 31));
        jPanel2.add(B_Tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 154, 30));
        jPanel2.add(B_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 154, 32));
        jPanel2.add(B_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 154, 29));
        jPanel2.add(B_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 154, 33));

        Buscar.setText("BUSCAR");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel2.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 163, 60));

        jLabel32.setText("Costo:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));
        jPanel2.add(B_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 154, 35));
        jPanel2.add(iconopro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));

        jTabbedPane1.addTab("BUSCAR", jPanel2);

        jPanel3.setBackground(new java.awt.Color(14, 176, 68));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Código:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel17.setText("Nombre:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel18.setText("Color:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel19.setText("Tamaño:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel20.setText("Stock:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel21.setText("Costo:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jLabel22.setText("Precio:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        jLabel23.setText("Edad Recomendada:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));
        jPanel3.add(M_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 148, 37));
        jPanel3.add(M_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 148, 36));
        jPanel3.add(M_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 148, 36));
        jPanel3.add(M_Tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 148, 42));
        jPanel3.add(M_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 148, 44));
        jPanel3.add(M_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 148, 41));
        jPanel3.add(M_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 148, 39));
        jPanel3.add(M_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 148, 39));

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel3.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 130, 40));

        Listar2.setText("Listar");
        Listar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar2ActionPerformed(evt);
            }
        });
        jPanel3.add(Listar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 130, 40));
        jPanel3.add(iconopro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));

        jTabbedPane1.addTab("MODIFICAR", jPanel3);

        jPanel4.setBackground(new java.awt.Color(14, 176, 68));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("Código:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel25.setText("Nombre:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel26.setText("Color:");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel27.setText("Tamaño");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel28.setText("Stock:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jLabel29.setText("Costo:");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jLabel30.setText("Precio:");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel31.setText("Edad Recomendada:");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));
        jPanel4.add(E_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 140, 30));
        jPanel4.add(E_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 140, 30));
        jPanel4.add(E_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 140, 30));

        E_Tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_TamañoActionPerformed(evt);
            }
        });
        jPanel4.add(E_Tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 140, 30));
        jPanel4.add(E_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 140, 30));
        jPanel4.add(E_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 140, 30));
        jPanel4.add(E_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 140, 30));
        jPanel4.add(E_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 140, 30));

        Listar3.setText("LISTAR");
        Listar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar3ActionPerformed(evt);
            }
        });
        jPanel4.add(Listar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 130, 30));

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 130, 30));
        jPanel4.add(iconopro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 110, 100));

        jTabbedPane1.addTab("ELIMINAR", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
        dispose();
       Administrador inic = new Administrador();
       inic.setVisible(true);

    }//GEN-LAST:event_CerrarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here:
        Table.getDataVector().removeAllElements();
        String [] filas=  new String[8];
   
     for(int i=0;i<arreglovector.filas();i++){
          filas[0] = String.valueOf(arreglovector.get(i).getCodigo());
          filas[1] =arreglovector.get(i).getNombre();
          filas[2] = arreglovector.get(i).getColor();
           filas[3] =arreglovector.get(i).getTamaño();
           filas[4] =String.valueOf(arreglovector.get(i).getStock());
           filas[5] = String.valueOf(arreglovector.get(i).getPrecio());
          filas[6] = String.valueOf(arreglovector.get(i).getCosto());      
          filas[7] = arreglovector.get(i).getEdad_rec();
           Table.addRow(filas);   
           }   
        
    }//GEN-LAST:event_ListarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
         int cod=0;
   
         
   String nom;
   String col;
   String tam = null;
   int stk;
   String cost;
   String pre;
   String edad_r = null;
   cod=arreglovector.correlativo();
     
        if(Nombre.getText().isEmpty() || Precio.getText().isEmpty() || Costo.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"NO dejar carmpos vacíos");
        }
        else
        {
      nom=Nombre.getText();
      col =(String)Color.getSelectedItem();
      if(Pequeño.isSelected()){
            tam="Pequeño";
            
        }else if(Mediano.isSelected()){
            tam="Mediano";
        }
        else if (Grande.isSelected())
        {
            tam="Grande";
        }
      stk = Integer.parseInt(Stock.getValue().toString());
      cost=Costo.getText();
      pre=Precio.getText();
      
      if(jCheckBox1.isSelected()){
            edad_r="3+ años";
        
        }
      else if(jCheckBox2.isSelected()){
            edad_r="5+ años";
            
        }
         else if(jCheckBox3.isSelected()){
               edad_r="7+ años";
        }
         else if(jCheckBox4.isSelected()){
             edad_r="9+ años";
         }
        
      
      Producto dat=new Producto();
      dat.setCodigo(cod);
      dat.setNombre(nom);
      dat.setColor(col);
      dat.setTamaño(tam);
      dat.setStock(stk);
      dat.setPrecio(Float.parseFloat(pre));
      dat.setCosto(Float.parseFloat(cost));
      dat.setEdad_rec(edad_r);
      arreglovector.agregar_array(dat);
      arreglovector.grabarEnArchivo(dat);
        }
      Nombre.setText("");
      Costo.setText("");
      Precio.setText("");
      
    }//GEN-LAST:event_GuardarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        int cod=0;
        cod=Integer.parseInt(B_Codigo.getText());
        Producto dat=arreglovector.buscarcodigo(cod);
        
        if(dat.getNombre()!="Error"){
            B_Nombre.setText(dat.getNombre());
            B_Color.setText(dat.getColor());
            B_Tamaño.setText(dat.getTamaño());
            B_Stock.setText(String.valueOf(dat.getStock()));
            B_Precio.setText(String.valueOf(dat.getPrecio()));
            B_Costo.setText(String.valueOf(dat.getCosto()));
            B_Edad.setText(dat.getEdad_rec());
            
        }else{
            JOptionPane.showMessageDialog(null,"No existe código","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
         String Mnom;
         String Mcol;
         String Mtam;
         int Mstk;
         float Mpre;
         float Mcos;
         String Meda;
      
                 
        Mnom=M_Nombre.getText();
        
       Mcol=(String)M_Color.getText();
       
      
            Mtam=M_Tamaño.getText();
        
          
           Mstk=Integer.parseInt(M_Stock.getText());
          Mpre=Float.parseFloat(M_Precio.getText());
          Mcos= Float.parseFloat(M_Costo.getText());
          Meda=M_Edad.getText();
       
          
      
      

        boolean estado = arreglovector.modificar(Dmodificar,Mnom,Mcol, Mtam , Mstk, Mpre, Mcos, Meda);
        
        if(estado==true){
            JOptionPane.showMessageDialog(null,"Registro Modificado");
            arreglovector.grabarModificareliminar();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No se pudo Modificar","Error",JOptionPane.WARNING_MESSAGE);
            
        }
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void Listar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar2ActionPerformed
        // TODO add your handling code here:
        int cod=0;
        cod=Integer.parseInt(M_Codigo.getText());
        Dmodificar =arreglovector.buscarcodigo(cod);
        
        if(Dmodificar.getNombre()!="Error"){
            M_Nombre.setText(Dmodificar.getNombre());
            
            M_Color.setText(Dmodificar.getColor());
            M_Tamaño.setText(Dmodificar.getTamaño());
            M_Stock.setText(String.valueOf(Dmodificar.getStock()));
            M_Precio.setText(String.valueOf(Dmodificar.getPrecio()));
            M_Costo.setText(String.valueOf(Dmodificar.getCosto()));
            M_Edad.setText(Dmodificar.getEdad_rec());
            
            
            
        }else{
            JOptionPane.showMessageDialog(null,"No existe código","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Listar2ActionPerformed

    private void Listar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar3ActionPerformed
        // TODO add your handling code here:
        int cod=0;
        cod=Integer.parseInt(E_Codigo.getText());
        Deliminar=arreglovector.buscarcodigo(cod);
        
        if(Deliminar.getNombre()!="Error"){
            E_Nombre.setText(Deliminar.getNombre());
            E_Color.setText(Deliminar.getColor());
            E_Tamaño.setText(Deliminar.getTamaño());
            E_Stock.setText(String.valueOf(Deliminar.getStock()));
            E_Precio.setText(String.valueOf(Deliminar.getPrecio()));
            E_Costo.setText(String.valueOf(Deliminar.getCosto()));
            E_Edad.setText(Deliminar.getEdad_rec());
            
        }else{
            JOptionPane.showMessageDialog(null,"No existe código","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Listar3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(Deliminar.getNombre()!="Error"){
            
            arreglovector.eliminar(Deliminar);
            JOptionPane.showMessageDialog(null,"Registro Eliminado");
            arreglovector.grabarModificareliminar();
        }else{
              JOptionPane.showMessageDialog(null,"No existe código","Error",JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void E_TamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_TamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_TamañoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField B_Codigo;
    private javax.swing.JTextField B_Color;
    private javax.swing.JTextField B_Costo;
    private javax.swing.JTextField B_Edad;
    private javax.swing.JTextField B_Nombre;
    private javax.swing.JTextField B_Precio;
    private javax.swing.JTextField B_Stock;
    private javax.swing.JTextField B_Tamaño;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cerrar;
    private javax.swing.JComboBox<String> Color;
    private javax.swing.JTextField Costo;
    private javax.swing.JTextField E_Codigo;
    private javax.swing.JTextField E_Color;
    private javax.swing.JTextField E_Costo;
    private javax.swing.JTextField E_Edad;
    private javax.swing.JTextField E_Nombre;
    private javax.swing.JTextField E_Precio;
    private javax.swing.JTextField E_Stock;
    private javax.swing.JTextField E_Tamaño;
    private javax.swing.JRadioButton Grande;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Listar;
    private javax.swing.JButton Listar2;
    private javax.swing.JButton Listar3;
    private javax.swing.JTextField M_Codigo;
    private javax.swing.JTextField M_Color;
    private javax.swing.JTextField M_Costo;
    private javax.swing.JTextField M_Edad;
    private javax.swing.JTextField M_Nombre;
    private javax.swing.JTextField M_Precio;
    private javax.swing.JTextField M_Stock;
    private javax.swing.JTextField M_Tamaño;
    private javax.swing.JRadioButton Mediano;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JRadioButton Pequeño;
    private javax.swing.JTextField Precio;
    private javax.swing.JSpinner Stock;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel iconopro;
    private javax.swing.JLabel iconopro1;
    private javax.swing.JLabel iconopro2;
    private javax.swing.JLabel iconopro3;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
